### ISSUE TITLE
Need docker compose image for edgex-taf testing

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/ci-build-images#109]
Docker compose image in https://hub.docker.com/r/docker/compose/ is only supported x86_64, when we test functional testing using both env, x86_64 and arm64. We have to build compose by ourselves.

**Comment by jamesrgregg** [comment]
Are you saying there’s no public image available?
I’m not clear on the ask from DevOps here.

**Comment by jamesrgregg** [comment]
@vishwassp-hcl-intel 
This might be related to the user story I asked you to look at earlier today.

**Comment by vishwassp-hcl-intel** [comment]
> @vishwassp-hcl-intel
> This might be related to the user story I asked you to look at earlier today.

Sure, I have asked a question to @cherrycl on this via slack. I shall proceed once I get the clarity

**Comment by cloudxxx8** [comment]
@cherrycl please elaborate what exactly we need the help from DevOp's team here.  Also, please share the steps how we build the image internally.

@jamesrgregg thanks for taking care of this issue.  there is no public/official compose image for ARM architecture, only for x86_64.

**Comment by cherrycl** [comment]
@vishwassp-hcl-intel The [Jenkinsfile](https://github.com/cherrycl/ci-build-images/blob/issue-109/Jenkinsfile) I prepared which is similar with [edgeXBuildDocker.groovy](https://github.com/edgexfoundry/edgex-global-pipelines/blob/master/vars/edgeXBuildDocker.groovy). 
When building compose image, we clone the compose repository first. Only add [checkout stage](https://github.com/cherrycl/ci-build-images/blob/3ad9117f92f3aa07861d252f275531cd88322c37/Jenkinsfile#L91) before executing docker build.

**Comment by vishwassp-hcl-intel** [comment]
@cherrycl did you try this image as it is ? [docker/compose:alpine-1.26.0-rc2](https://hub.docker.com/layers/docker/compose/alpine-1.25.4/images/sha256-390bdf3da99a622f5c11f4db386dd97f2858db30cfed07d000b867f1fb25b2f7?context=explore). As this one seems to be alpine based, I think it should support both.

**Comment by cherrycl** [comment]
@vishwassp-hcl-intel I got the following error when using the image you mentioned.
```
10:38:10  INFO:EdgeX deployment:Digest: sha256:1b9cc85cfd55f78d661e4f2e6ae498bd826610445d93d96d2e5ab647b7fdf305
10:38:10  
10:38:10  INFO:EdgeX deployment:Status: Downloaded newer image for docker/compose:alpine-1.26.0-rc2
10:38:10  
10:38:12  INFO:EdgeX deployment:standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by vishwassp-hcl-intel** [comment]
@cherrycl , Are you using this inside some scripts ? Could you please confirm if the below solution works for you ?
[exec-format-error](https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error)

**Comment by cherrycl** [comment]
@vishwassp-hcl-intel Yes, I ran the 'docker run' command inside some shell script. I tried the solution you provided and still got "exec format error" after changing '#!/bin/sh' to '#!/bin/bash'.
The second solution you provided on slack, that seems the same as what I did on the Jenkinsfile.
Would you please help to create a "compose" branch on this repository, then I can open PR?

**Comment by vishwassp-hcl-intel** [comment]
@cherrycl , After the discussion with the team, we thought below is the right approach to handle this.
Just install the docker-compose on the host using below command.
sudo apt install -y --no-install-recommends docker-compose

**Comment by cloudxxx8** [comment]
@vishwassp-hcl-intel 
`sudo apt install -y --no-install-recommends docker-compose` would only use the older version of docker-compose, and it is limited the capability to use some new feature of docker-compose.
Anyway, the work has been done in #120, and we have verified on sandbox.
May I know reason you said install the docker-compose on the host is the right approach?

**Comment by vishwassp-hcl-intel** [comment]
@cloudxxx8 , There were two approaches to it..
1. clone the docker-compose repo, build it and use it - 
    Myself and Cherry discussed on this and looks like #120 implemented in the same way.
2. Inside the Docker container (ARM), install the docker-compose as specified (above). 
   I suggested this to avoid cloning of docker-compose repo and build it. But, if the installation procedure is not giving you the right version, then you can go with option1 (#120 ) itself.

I hope we can close this request.

**Comment by cloudxxx8** [comment]
@vishwassp-hcl-intel thanks for the explanation
I prefer option 1, because we can control the version in the future, and we only need to build it when necessary.
Let's close this issue once I get @ernestojeda 's agreement.

**Comment by ernestojeda** [comment]
> @vishwassp-hcl-intel thanks for the explanation
> I prefer option 1, because we can control the version in the future, and we only need to build it when necessary.
> Let's close this issue once I get @ernestojeda 's agreement.

I was more concerned with build time and complexity of maintaining this Dockerfile. I was not aware that you required more up-to-date versions of docker-compose. I am ok with this if this is what is required.

**Comment by jamesrgregg** [comment]
https://github.com/edgexfoundry/ci-build-images/pull/120
