### ISSUE TITLE
Snapcraft Build Image needs to be updated more frequently

### ISSUE THREAD

**Issue by ernestojeda** [edgexfoundry/ci-build-images#141]
After a conversation with Ian Johnson from Canonical, he mentioned that snapcraft is updated regularly and snaps work best with the most up to date version of snapcraft.

We will need to update edgeXBuildDocker to add a cron trigger if specified in the config.

**Comment by jamesrgregg** [comment]
[US7212](https://rally1.rallydev.com/#/detail/userstory/423668481200?fdp=true): EdgeX DevOps: Snapcraft Build Image needs to be updated more frequently

**Comment by ernestojeda** [comment]
Not needed anymore. Canonical is moving away from docker for building snaps.

**Comment by ernestojeda** [comment]
See comment from this PR: https://github.com/edgexfoundry/ci-management/pull/629#issuecomment-699052405
