### ISSUE TITLE
Robotframework and Compose image build request

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/ci-build-images#35]
Request to build Robotframework and Compose image.

- Robotframework docker image for x86_64 and arm64
- Compose docker image for x86_64 and arm64

**Comment by weichou1229** [comment]
@jamesrgregg 
Could you help create Jenkins job for building these docker images?

- Robotframework x86_64
- Robotframework arm64
- Compose x86_64
- Compose arm64

https://github.com/edgexfoundry/ci-build-images/pull/36

**Comment by jamesrgregg** [comment]
issue addressed in #36
