### ISSUE TITLE
Create the edgex-taf docker image build job

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/ci-build-images#74]
Create a build job for edgex-taf, this is used for trigger automation testing project like device service test, blackbox-testing, performance-summary-collection.

The edgex-taf project still under the holding area but we can build the image first.
https://github.com/edgexfoundry-holding/edgex-taf
https://github.com/edgexfoundry-holding/edgex-taf-common

**Comment by jamesrgregg** [comment]
PR#75 was closed per update from Bruce ww38.5
