### ISSUE TITLE
Fix Kong base build image for aarch64 to address issue in blackbox-testing

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-build-images#78]
Fix Kong base build image for aarch64 to address issue in blackbox-testing

**Comment by jamesrgregg** [comment]
[US5462](https://rally1.rallydev.com/#/detail/userstory/337107759184?fdp=true)

**Comment by ernestojeda** [comment]
More details...The base image for the kong images was `hypriot/rpi-alpine` which is based on `armhf/alpine` which supports only arm32v7 and arm32v6. I created a new parent `ernestoojeda/rpi-aline:arm64` which is based on `FROM arm64v8/alpine:3.9`.  I am still waiting on verification to make sure the fix works.
